<a href="https://colab.research.google.com/github/fathimathulaifa/ICT-assessments-and-assignments/blob/main/Intermediate_Assessment_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Analyzing sales Data in an E-commerce Store**

Context
You are a Data Analyst at "ShopEase," an online retail store. The
company wants a preliminary analysis of customer purchases to
identify trends and automate simple summary analytics. You have
been provided with a basic CSV of sales transactions (to be simulated
by creating a list of dictionaries in Python).

1.1 Simulate a dataset of 10 sales records as a list of dictionaries.
Each sale should contain: order_id (int), customer (str), item (str),
quantity (int), price_per_item (float, in INR), order_date (str,
'YYYY-MM-DD').
Write a snippet to create this data. Print out the dataset.

In [1]:

sales_dat = [
    {"order_id": 10, "customer": "Alex", "item": "Laptop", "quantity": 1, "price_per_item": 50000.0, "order_date": "2025-12-01"},
    {"order_id": 11, "customer": "Alice", "item": "Headphones", "quantity": 2, "price_per_item": 1500.0, "order_date": "2025-12-02"},
    {"order_id": 12, "customer": "Charles", "item": "Smartphone", "quantity": 1, "price_per_item": 30000.0, "order_date": "2025-12-03"},
    {"order_id": 13, "customer": "David", "item": "Laptop", "quantity": 1, "price_per_item": 55000.0, "order_date": "2025-12-04"},
    {"order_id": 14, "customer": "Darshan", "item": "Keyboard", "quantity": 3, "price_per_item": 1200.0, "order_date": "2025-12-05"},
    {"order_id": 15, "customer": "Joy", "item": "Mouse", "quantity": 2, "price_per_item": 800.0, "order_date": "2025-12-06"},
    {"order_id": 16, "customer": "Lily", "item": "Monitor", "quantity": 1, "price_per_item": 12000.0, "order_date": "2025-12-07"},
    {"order_id": 17, "customer": "Simon", "item": "Smartphone", "quantity": 2, "price_per_item": 28000.0, "order_date": "2025-12-08"},
    {"order_id": 18, "customer": "James", "item": "Headphones", "quantity": 1, "price_per_item": 1600.0, "order_date": "2025-12-09"},
    {"order_id": 19, "customer": "Arun", "item": "Laptop", "quantity": 1, "price_per_item": 52000.0, "order_date": "2025-12-10"},
]

Created a dataset of 10 sales records as a list of dictionaries to simulate e-commerce transactions.

In [3]:

# Display the data
for sale in sales_dat:
    print(sale)

{'order_id': 10, 'customer': 'Alex', 'item': 'Laptop', 'quantity': 1, 'price_per_item': 50000.0, 'order_date': '2025-12-01'}
{'order_id': 11, 'customer': 'Alice', 'item': 'Headphones', 'quantity': 2, 'price_per_item': 1500.0, 'order_date': '2025-12-02'}
{'order_id': 12, 'customer': 'Charles', 'item': 'Smartphone', 'quantity': 1, 'price_per_item': 30000.0, 'order_date': '2025-12-03'}
{'order_id': 13, 'customer': 'David', 'item': 'Laptop', 'quantity': 1, 'price_per_item': 55000.0, 'order_date': '2025-12-04'}
{'order_id': 14, 'customer': 'Darshan', 'item': 'Keyboard', 'quantity': 3, 'price_per_item': 1200.0, 'order_date': '2025-12-05'}
{'order_id': 15, 'customer': 'Joy', 'item': 'Mouse', 'quantity': 2, 'price_per_item': 800.0, 'order_date': '2025-12-06'}
{'order_id': 16, 'customer': 'Lily', 'item': 'Monitor', 'quantity': 1, 'price_per_item': 12000.0, 'order_date': '2025-12-07'}
{'order_id': 17, 'customer': 'Simon', 'item': 'Smartphone', 'quantity': 2, 'price_per_item': 28000.0, 'order_date': '2025-12-08'}
{'order_id': 18, 'customer': 'James', 'item': 'Headphones', 'quantity': 1, 'price_per_item': 1600.0, 'order_date': '2025-12-09'}
{'order_id': 19, 'customer': 'Arun', 'item': 'Laptop', 'quantity': 1, 'price_per_item': 52000.0, 'order_date': '2025-12-10'}

 2.1 Calculate the total revenue for the store (sum of all quantities ×
price per item).

In [9]:
# Calculate total revenue
total_revenue = sum(sale["quantity"] * sale["price_per_item"] for sale in sales_dat)
print("Total Revenue (INR):", total_revenue)

Total Revenue (INR): 264800.0

In [10]:
import pandas as pd

df = pd.DataFrame(sales_dat)
df

,order_id,customer,item,quantity,price_per_item,order_date,total_sale
0,10,Alex,Laptop,1,50000.0,2025-12-01,50000.0
1,11,Alice,Headphones,2,1500.0,2025-12-02,3000.0
2,12,Charles,Smartphone,1,30000.0,2025-12-03,30000.0
3,13,David,Laptop,1,55000.0,2025-12-04,55000.0
4,14,Darshan,Keyboard,3,1200.0,2025-12-05,3600.0
5,15,Joy,Mouse,2,800.0,2025-12-06,1600.0
6,16,Lily,Monitor,1,12000.0,2025-12-07,12000.0
7,17,Simon,Smartphone,2,28000.0,2025-12-08,56000.0
8,18,James,Headphones,1,1600.0,2025-12-09,1600.0
9,19,Arun,Laptop,1,52000.0,2025-12-10,52000.0

2.2 Identify all orders where the total order value (quantity × price
per item) exceeds ₹2,000. Store the result as a new list.

In [12]:
# Identify orders with total order value > 2000
high_value_orders = [sale for sale in sales_dat if sale["quantity"] * sale["price_per_item"] > 2000]

# Print high-value orders
print("\nOrders with total value > ₹2,000:")
for order in high_value_orders:
    print(order)

Orders with total value > ₹2,000:
{'order_id': 10, 'customer': 'Alex', 'item': 'Laptop', 'quantity': 1, 'price_per_item': 50000.0, 'order_date': '2025-12-01', 'total_sale': 50000.0}
{'order_id': 11, 'customer': 'Alice', 'item': 'Headphones', 'quantity': 2, 'price_per_item': 1500.0, 'order_date': '2025-12-02', 'total_sale': 3000.0}
{'order_id': 12, 'customer': 'Charles', 'item': 'Smartphone', 'quantity': 1, 'price_per_item': 30000.0, 'order_date': '2025-12-03', 'total_sale': 30000.0}
{'order_id': 13, 'customer': 'David', 'item': 'Laptop', 'quantity': 1, 'price_per_item': 55000.0, 'order_date': '2025-12-04', 'total_sale': 55000.0}
{'order_id': 14, 'customer': 'Darshan', 'item': 'Keyboard', 'quantity': 3, 'price_per_item': 1200.0, 'order_date': '2025-12-05', 'total_sale': 3600.0}
{'order_id': 16, 'customer': 'Lily', 'item': 'Monitor', 'quantity': 1, 'price_per_item': 12000.0, 'order_date': '2025-12-07', 'total_sale': 12000.0}
{'order_id': 17, 'customer': 'Simon', 'item': 'Smartphone', 'quantity': 2, 'price_per_item': 28000.0, 'order_date': '2025-12-08', 'total_sale': 56000.0}
{'order_id': 19, 'customer': 'Arun', 'item': 'Laptop', 'quantity': 1, 'price_per_item': 52000.0, 'order_date': '2025-12-10', 'total_sale': 52000.0}

In [13]:

df_h= pd.DataFrame(high_value_orders)
df_h

,order_id,customer,item,quantity,price_per_item,order_date,total_sale
0,10,Alex,Laptop,1,50000.0,2025-12-01,50000.0
1,11,Alice,Headphones,2,1500.0,2025-12-02,3000.0
2,12,Charles,Smartphone,1,30000.0,2025-12-03,30000.0
3,13,David,Laptop,1,55000.0,2025-12-04,55000.0
4,14,Darshan,Keyboard,3,1200.0,2025-12-05,3600.0
5,16,Lily,Monitor,1,12000.0,2025-12-07,12000.0
6,17,Simon,Smartphone,2,28000.0,2025-12-08,56000.0
7,19,Arun,Laptop,1,52000.0,2025-12-10,52000.0

2.3 Find the item with the highest total quantity sold across all
orders.

In [16]:
# Dictionary to store total quantity per item
qty = {}

# Add quantities for each item
for s in sales_dat:
    qty[s["item"]] = qty.get(s["item"], 0) + s["quantity"]

# Find the item with highest quantity
top_item = max(qty, key=qty.get)

# Print the result
print("Item with highest total quantity sold:", top_item, "\nQuantity:", qty[top_item])

Item with highest total quantity sold: Laptop
Quantity: 3

* 3.1 Write a function apply_discount(orders, discount_rate) that takes
a list of orders and applies a percentage discount (e.g., 10% = 0.10) to
the price_per_item for each order.
Return a new list of orders (do not modify the original list).
* 3.2 Explain, with a code example in your script, the difference
between local and global variable scope in Python.

In [17]:
#3.1

# Convert list of orders to DataFrame
df_orders = pd.DataFrame(sales_dat)

# Apply discount (10%) without changing original
df_discounted = df_orders.copy()
df_discounted["price_per_item"] = df_discounted["price_per_item"] * 0.9  # 10% discount

# Show first 3 orders
df_discounted.head(3)

,order_id,customer,item,quantity,price_per_item,order_date,total_sale
0,10,Alex,Laptop,1,45000.0,2025-12-01,50000.0
1,11,Alice,Headphones,2,1350.0,2025-12-02,3000.0
2,12,Charles,Smartphone,1,27000.0,2025-12-03,30000.0

3.2  A global variable is created outside any function and can be used anywhere in the program.
A local variable is created inside a function and can only be used inside that function.

In [18]:
# 3.2
# Global variable
x = 100  # can be used anywhere

def demo_scope():
    # Local variable
    y = 50  # only exists inside this function
    print("Inside function:")
    print("x (global) =", x)
    print("y (local)  =", y)

demo_scope()

print("Outside function:")
print("x (global) =", x)
# print("y (local) =", y)  #  this line will give an error

Inside function:
x (global) = 100
y (local)  = 50
Outside function:
x (global) = 100



* 4.1 Write a custom iterator class OrderIterator to iterate through the
orders, yielding one order at a time.

* 4.2 Create a dictionary grouping all orders by customer using a
dictionary comprehension.

In [19]:
# 4.1
class OrderIterator:
    def __init__(self, orders):
        self.o = orders  # store orders
        self.i = 0       # start index

    def __iter__(self):
        return self

    def __next__(self):
        if self.i < len(self.o):
            order = self.o[self.i]
            self.i += 1
            return order
        else:
            raise StopIteration

In [20]:
# Example usage
it = OrderIterator(sales_dat)
for order in it:
    print(order)

{'order_id': 10, 'customer': 'Alex', 'item': 'Laptop', 'quantity': 1, 'price_per_item': 50000.0, 'order_date': '2025-12-01', 'total_sale': 50000.0}
{'order_id': 11, 'customer': 'Alice', 'item': 'Headphones', 'quantity': 2, 'price_per_item': 1500.0, 'order_date': '2025-12-02', 'total_sale': 3000.0}
{'order_id': 12, 'customer': 'Charles', 'item': 'Smartphone', 'quantity': 1, 'price_per_item': 30000.0, 'order_date': '2025-12-03', 'total_sale': 30000.0}
{'order_id': 13, 'customer': 'David', 'item': 'Laptop', 'quantity': 1, 'price_per_item': 55000.0, 'order_date': '2025-12-04', 'total_sale': 55000.0}
{'order_id': 14, 'customer': 'Darshan', 'item': 'Keyboard', 'quantity': 3, 'price_per_item': 1200.0, 'order_date': '2025-12-05', 'total_sale': 3600.0}
{'order_id': 15, 'customer': 'Joy', 'item': 'Mouse', 'quantity': 2, 'price_per_item': 800.0, 'order_date': '2025-12-06', 'total_sale': 1600.0}
{'order_id': 16, 'customer': 'Lily', 'item': 'Monitor', 'quantity': 1, 'price_per_item': 12000.0, 'order_date': '2025-12-07', 'total_sale': 12000.0}
{'order_id': 17, 'customer': 'Simon', 'item': 'Smartphone', 'quantity': 2, 'price_per_item': 28000.0, 'order_date': '2025-12-08', 'total_sale': 56000.0}
{'order_id': 18, 'customer': 'James', 'item': 'Headphones', 'quantity': 1, 'price_per_item': 1600.0, 'order_date': '2025-12-09', 'total_sale': 1600.0}
{'order_id': 19, 'customer': 'Arun', 'item': 'Laptop', 'quantity': 1, 'price_per_item': 52000.0, 'order_date': '2025-12-10', 'total_sale': 52000.0}

In [21]:

it = OrderIterator(sales_dat)

# Collect orders in a list
orders_list = [order for order in it]

# Convert to DataFrame for table format
df_orders = pd.DataFrame(orders_list)

# Display the table
df_orders

,order_id,customer,item,quantity,price_per_item,order_date,total_sale
0,10,Alex,Laptop,1,50000.0,2025-12-01,50000.0
1,11,Alice,Headphones,2,1500.0,2025-12-02,3000.0
2,12,Charles,Smartphone,1,30000.0,2025-12-03,30000.0
3,13,David,Laptop,1,55000.0,2025-12-04,55000.0
4,14,Darshan,Keyboard,3,1200.0,2025-12-05,3600.0
5,15,Joy,Mouse,2,800.0,2025-12-06,1600.0
6,16,Lily,Monitor,1,12000.0,2025-12-07,12000.0
7,17,Simon,Smartphone,2,28000.0,2025-12-08,56000.0
8,18,James,Headphones,1,1600.0,2025-12-09,1600.0
9,19,Arun,Laptop,1,52000.0,2025-12-10,52000.0

In [23]:
# 4.2
#Group orders by customer using dictionary comprehension
orders_by_customer = {cust: [o for o in sales_dat if o["customer"] == cust]
                      for cust in set(o["customer"] for o in sales_dat)}

# Print the grouped dictionary
for cust, orders in orders_by_customer.items():
    print("\nCustomer:", cust)
    for order in orders:
        print(order)

Customer: Alex
{'order_id': 10, 'customer': 'Alex', 'item': 'Laptop', 'quantity': 1, 'price_per_item': 50000.0, 'order_date': '2025-12-01', 'total_sale': 50000.0}

Customer: James
{'order_id': 18, 'customer': 'James', 'item': 'Headphones', 'quantity': 1, 'price_per_item': 1600.0, 'order_date': '2025-12-09', 'total_sale': 1600.0}

Customer: Charles
{'order_id': 12, 'customer': 'Charles', 'item': 'Smartphone', 'quantity': 1, 'price_per_item': 30000.0, 'order_date': '2025-12-03', 'total_sale': 30000.0}

Customer: David
{'order_id': 13, 'customer': 'David', 'item': 'Laptop', 'quantity': 1, 'price_per_item': 55000.0, 'order_date': '2025-12-04', 'total_sale': 55000.0}

Customer: Joy
{'order_id': 15, 'customer': 'Joy', 'item': 'Mouse', 'quantity': 2, 'price_per_item': 800.0, 'order_date': '2025-12-06', 'total_sale': 1600.0}

Customer: Simon
{'order_id': 17, 'customer': 'Simon', 'item': 'Smartphone', 'quantity': 2, 'price_per_item': 28000.0, 'order_date': '2025-12-08', 'total_sale': 56000.0}

Customer: Arun
{'order_id': 19, 'customer': 'Arun', 'item': 'Laptop', 'quantity': 1, 'price_per_item': 52000.0, 'order_date': '2025-12-10', 'total_sale': 52000.0}

Customer: Lily
{'order_id': 16, 'customer': 'Lily', 'item': 'Monitor', 'quantity': 1, 'price_per_item': 12000.0, 'order_date': '2025-12-07', 'total_sale': 12000.0}

Customer: Darshan
{'order_id': 14, 'customer': 'Darshan', 'item': 'Keyboard', 'quantity': 3, 'price_per_item': 1200.0, 'order_date': '2025-12-05', 'total_sale': 3600.0}

Customer: Alice
{'order_id': 11, 'customer': 'Alice', 'item': 'Headphones', 'quantity': 2, 'price_per_item': 1500.0, 'order_date': '2025-12-02', 'total_sale': 3000.0}

In [24]:


for cust, orders in orders_by_customer.items():
    print(f"\nCustomer: {cust}")
    df = pd.DataFrame(orders)
    display(df)

Customer: Alex

   order_id customer    item  quantity  price_per_item  order_date  total_sale
0        10     Alex  Laptop         1         50000.0  2025-12-01     50000.0

Customer: James

,order_id,customer,item,quantity,price_per_item,order_date,total_sale
0,18,James,Headphones,1,1600.0,2025-12-09,1600.0

Customer: Charles

,order_id,customer,item,quantity,price_per_item,order_date,total_sale
0,12,Charles,Smartphone,1,30000.0,2025-12-03,30000.0

Customer: David

   order_id customer    item  quantity  price_per_item  order_date  total_sale
0        13    David  Laptop         1         55000.0  2025-12-04     55000.0

Customer: Joy

   order_id customer   item  quantity  price_per_item  order_date  total_sale
0        15      Joy  Mouse         2           800.0  2025-12-06      1600.0

Customer: Simon

,order_id,customer,item,quantity,price_per_item,order_date,total_sale
0,17,Simon,Smartphone,2,28000.0,2025-12-08,56000.0

Customer: Arun

   order_id customer    item  quantity  price_per_item  order_date  total_sale
0        19     Arun  Laptop         1         52000.0  2025-12-10     52000.0

Customer: Lily

,order_id,customer,item,quantity,price_per_item,order_date,total_sale
0,16,Lily,Monitor,1,12000.0,2025-12-07,12000.0

Customer: Darshan

,order_id,customer,item,quantity,price_per_item,order_date,total_sale
0,14,Darshan,Keyboard,3,1200.0,2025-12-05,3600.0

Customer: Alice

,order_id,customer,item,quantity,price_per_item,order_date,total_sale
0,11,Alice,Headphones,2,1500.0,2025-12-02,3000.0